### ISSUE TITLE
Difference in processing of Chinese vs other languages

### ISSUE THREAD

**Issue by tarun360** [Betswish/Cross-Lingual-Consistency#2]
Hello,

Can you explain the following processing steps are different for Chinese vs other languages?

https://github.com/Betswish/Cross-Lingual-Consistency/blob/d738399b5e34b1412de40e84f28925cb74b04442/1_easyrun/main.py#L57-L62

**Comment by Betswish** [comment]
Hi @tarun360 , thanks for reading our paper and code!
Regarding the implementation of the knowledge probing metric here, we referred to the previous work (https://github.com/WadeYin9712/GeoMLAMA/blob/main/test_mlm_w_mask.py).

At the time when the code was being built up, the decoder-only models would sometimes add a special token at the end of the non-Chinese sentences during tokenization. So those lines were used to remove the special tokens.

However, with the update of Transformers and Huggingface Tokenizers, we found now that the issue didn't exist anymore. So we just unified the codes for all languages. (Also, we fixed a bug that BLOOM Tokenizer will not automatically add the BOS Token at the beginning of the sentence in the latest update.)

Thank you again for pointing it out!
